name: Frontend CI

on:
  push:
    branches: [siwar-devops]
  pull_request:
    branches: [siwar-devops]

jobs:
  test:
    runs-on: ubuntu-22.04

    defaults:
      run:
        working-directory: main

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Install dependencies for ChromeHeadless
        run: |
          sudo apt-get update
          sudo apt-get install -y libnss3 libxss1 libasound2 libatk1.0-0 libatk-bridge2.0-0 libcups2 libdrm2 libxcomposite1 libxdamage1 libxrandr2 libgbm1 libpango1.0-0 libatspi2.0-0

      - name: Build Angular project
        run: npm run build -- --configuration production

      - name: Run tests
        run: npm run test -- --watch=false --browsers=ChromeHeadless
      # Docker login step
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: "siwarhmedi"
          password: "dckr_pat_Y1IxL8nvMfw2YGTXMZnFH9hhqno"

      # Docker build & push
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./main/Dockerfile
          push: true
          tags: siwarhmedi/materialm:latest